name: Publish to Docker
on:
push:
branches:
-main
permissions:
packages: write
contents: read
jobs:
publish:
runs-on: ubuntu-latest
steps:
-name: checkout
uses: actions/checkout@v4
#Add your test steps here if needed...
-name: Docker meta
id: meta
uses: docker/metadata-action@v5
with:
images: ghcr.io/Kiranteja1894/publish-packages/game
tags: type=sha
-name: login to GHCR
uses: docker/login-action@v3
with:
registry: ghcr.io
username: ${{github.repository_owner}}
password: ${{secrets.GIYHUB_TOKEN}}
-name: build container
uses: docker/build-push-action@v5
with:
context: .
push: true
tags: ${{steps.meta.output.tags}}
